package com.codecool.model.infopage;

public enum ConservationStatus {
	EXTINCT,
	EXTINCT_IN_THE_WILD,
	CRITICALLY_ENDANGERED,
	ENDANGERED,
	VULNERABLE,
	NEAR_THREATENED,
	LEAST_CONCERN,
	NOT_EVALUATED
}